{
    "openapi": "3.0.1",
    "info": {
        "title": "eFactura API Suite",
        "description": "A comprehensive suite of APIs for eFactura operations, including XML signature validation, message status retrieval, message listing, invoice upload and download, and XML to PDF transformation.",
        "version": "1.0"
    },
    "tags": [
        {
            "name": "XML Signature Validation",
            "description": "API for validating electronic signatures on electronic invoices."
        },
        {
            "name": "EFactura Message Status",
            "description": "API for retrieving the processing status of electronic invoice messages."
        },
        {
            "name": "EFactura Message List",
            "description": "API for listing electronic invoice messages with various filtering options."
        },
        {
            "name": "EFactura Upload",
            "description": "API for uploading electronic invoice XML files."
        },
        {
            "name": "eFactura Download",
            "description": "Descarcare factura API"
        },
        {
            "name": "EFactura Validation",
            "description": "EFactura Validare API"
        },
        {
            "name": "EFacturaXmlToPdf",
            "description": "EFactura XmlToPdf API"
        }
    ],
    "paths": {
        "/listaMesajePaginatieFactura": {
            "get": {
                "tags": [
                    "EFactura Message List"
                ],
                "operationId": "getPaginatie",
                "parameters": [
                    {
                        "name": "startTime",
                        "in": "query",
                        "description": "Data de start a intervalului interogat. Este in format Unix Time exprimat in milisecunde [1646037374000 = 28.02.2022 10:36:14]",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": 1646037374000
                    },
                    {
                        "name": "endTime",
                        "in": "query",
                        "description": "Data de final a intervalului interogat. Este in format Unix Time exprimat in milisecunde [1646170574000 = 01.03.2022 23:36:14]",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": 1646170574000
                    },
                    {
                        "name": "cif",
                        "in": "query",
                        "description": "CIF",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": 8000000000
                    },
                    {
                        "name": "pagina",
                        "in": "query",
                        "description": "Pagina curenta ",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": 1
                    },
                    {
                        "name": "filtru",
                        "in": "query",
                        "description": "Folosit pentru filtrarea mesajelor. Parametrul poate sa lipseasca caz in care se intoarce toata lista de mesaje. Daca este prezent valoarile acceptate sunt E,P,T sau R",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "example": "E"
                    }
                ],
                "responses": {
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/GeneralErrorMessage"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Response code 400",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/GeneralErrorMessage"
                                },
                                "examples": {
                                    "lipsa startTime, endTime, cif sau pagina": {
                                        "description": "Parametrii startTime, endTime, cif si pagina sunt obligatorii",
                                        "value": {
                                            "timestamp": "19-08-2021 11:59:29",
                                            "status": 400,
                                            "error": "Bad Request",
                                            "message": "Parametrii startTime, endTime, cif si pagina sunt obligatorii"
                                        }
                                    },
                                    "cif este non numeric": {
                                        "description": "cif non-numeric",
                                        "value": {
                                            "eroare": "CIF introdus= aaa nu este un numar sau nu are o valoare acceptata de sistem",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "startTime nu este un numar sau nu are o valoare acceptata de sistem": {
                                        "description": "startTime non-numeric",
                                        "value": {
                                            "eroare": "startTime = aaa nu este un numar sau nu are o valoare acceptata de sistem",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "endTime nu este un numar sau nu are o valoare acceptata de sistem": {
                                        "description": "endTime non-numeric",
                                        "value": {
                                            "eroare": "endTime = aaa nu este un numar sau nu are o valoare acceptata de sistem",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "pagina nu este un numar sau nu are o valoare acceptata de sistem": {
                                        "description": "pagina non-numeric",
                                        "value": {
                                            "eroare": "pagina = aa nu este un numar sau nu are o valoare acceptata de sistem",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "startTime mai vechi de 60 de zile": {
                                        "description": "startTime mai vechi de 60 de zile",
                                        "value": {
                                            "eroare": "startTime = 09-07-2022 10:41:11 nu poate fi mai vechi de 60 de zile fata de momentul requestului",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "endTime inainte de startTime": {
                                        "description": "endTime nu poate fi inainte de startTime",
                                        "value": {
                                            "eroare": "endTime = 09-08-2022 10:41:11 nu poate fi <= startTime = 06-09-2022 09:48:20",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "endTime in viitor": {
                                        "description": "endTime nu poate fi o data din viitor",
                                        "value": {
                                            "eroare": "endTime = 02-12-2022 11:49:24 nu poate in viitor fata de momentul requestului",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "parametrul filtru invalid": {
                                        "description": "parametrul filtru este completat dar este invalid",
                                        "value": {
                                            "eroare": "Valorile acceptate pentru parametrul filtru sunt E, T, P sau R",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "nu aveti drept pentru acest cif": {
                                        "description": "cif fara drept",
                                        "value": {
                                            "eroare": "Nu aveti drept in SPV pentru CIF=8000000000",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "lipsa drepturi SPV": {
                                        "description": "nu aveti drepturi in SPV pentru nici un cif",
                                        "value": {
                                            "eroare": "Nu exista niciun CIF pentru care sa aveti drept in SPV",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "paginia mai mare decat total pagini": {
                                        "description": "pagina solicitata depaseste numarul total de pagini",
                                        "value": {
                                            "eroare": "Pagina solicitata 50 este mai mare decat numarul toatal de pagini 29",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "nu exista mesaje": {
                                        "description": "nu exista mesaje in intervalul mentionat ",
                                        "value": {
                                            "eroare": "Nu exista mesaje in intervalul selectat",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "limita apeluri zilnice atinsa": {
                                        "description": "a fost atinsa limita de apeluri zilnice",
                                        "value": {
                                            "eroare": "S-au facut deja 1000 interogari de lista mesaje de catre utilizator in cursul zilei",
                                            "titlu": "Lista Mesaje"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "Response code 200",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "mesaje": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/EfacturaDetailedMessage"
                                            }
                                        },
                                        "numar_inregistrari_in_pagina": {
                                            "type": "integer"
                                        },
                                        "numar_total_inregistrari_per_pagina": {
                                            "type": "integer"
                                        },
                                        "numar_total_inregistrari": {
                                            "type": "integer"
                                        },
                                        "numar_total_pagini": {
                                            "type": "integer"
                                        },
                                        "index_pagina_curenta": {
                                            "type": "integer"
                                        },
                                        "serial": {
                                            "type": "string"
                                        },
                                        "cui": {
                                            "type": "string"
                                        },
                                        "titlu": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "cif-ul returneaza mesaje": {
                                        "description": "a fost intoarsa lista de mesaje",
                                        "value": {
                                            "mesaje": [
                                                {
                                                    "data_creare": "202210311452",
                                                    "cif": "8000000000",
                                                    "id_solicitare": "5001120362",
                                                    "detalii": "Erori de validare identificate la factura primita cu id_incarcare=5001120362",
                                                    "tip": "ERORI FACTURA",
                                                    "id": "3001474425"
                                                },
                                                {
                                                    "data_creare": "202210311452",
                                                    "cif": "8000000000",
                                                    "id_solicitare": "5001120366",
                                                    "detalii": "Erori de validare identificate la factura primita cu id_incarcare=5001120366",
                                                    "tip": "ERORI FACTURA",
                                                    "id": "3001474424"
                                                }
                                            ],
                                            "numar_inregistrari_in_pagina": 2,
                                            "numar_total_inregistrari_per_pagina": 500,
                                            "numar_total_inregistrari": 14130,
                                            "numar_total_pagini": 29,
                                            "index_pagina_curenta": 29,
                                            "serial": "1234AA456",
                                            "cui": "8000000000",
                                            "titlu": "Lista Mesaje disponibile din intervalul 06-09-2022 09:48:20 - 02-11-2022 11:49:24"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/listaMesajeFactura": {
            "get": {
                "tags": [
                    "EFactura Message List"
                ],
                "operationId": "getListaMesaje",
                "parameters": [
                    {
                        "name": "zile",
                        "in": "query",
                        "description": "Numarul de zile pentru care se face interogarea. Valoarea este 1 si 60",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": 50
                    },
                    {
                        "name": "cif",
                        "in": "query",
                        "description": "CIF",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": 8000000000
                    },
                    {
                        "name": "filtru",
                        "in": "query",
                        "description": "Folosit pentru filtrarea mesajelor. Parametrul poate sa lipseasca caz in care se intoarce toata lista de mesaje. Daca este prezent valoarile acceptate sunt E,P,T sau R",
                        "required": false,
                        "schema": {
                            "type": "string"
                        },
                        "example": "E"
                    }
                ],
                "responses": {
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/GeneralErrorMessage"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Response code 400",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/GeneralErrorMessage"
                                },
                                "examples": {
                                    "lipsa zile sau cif": {
                                        "description": "Nu ati completat parametrii zile sau cif",
                                        "value": {
                                            "timestamp": "19-08-2021 11:59:29",
                                            "status": 400,
                                            "error": "Bad Request",
                                            "message": "Parametrii zile si cif sunt obligatorii"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "Response code 200",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "mesaje": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/components/schemas/EfacturaDetailedMessage"
                                            }
                                        },
                                        "serial": {
                                            "type": "string"
                                        },
                                        "cui": {
                                            "type": "string"
                                        },
                                        "titlu": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "cif-ul returneaza mesaje": {
                                        "description": "a fost intoarsa lista de mesaje",
                                        "value": {
                                            "mesaje": [
                                                {
                                                    "data_creare": "202211011415",
                                                    "cif": "8000000000",
                                                    "id_solicitare": "5001130147",
                                                    "detalii": "Erori de validare identificate la factura primita cu id_incarcare=5001130147",
                                                    "tip": "ERORI FACTURA",
                                                    "id": "3001293434"
                                                },
                                                {
                                                    "data_creare": "202211011336",
                                                    "cif": "8000000000",
                                                    "id_solicitare": "5001131297",
                                                    "detalii": "Factura cu id_incarcare=5001131297 emisa de cif_emitent=8000000000 pentru cif_beneficiar=3",
                                                    "tip": "FACTURA TRIMISA",
                                                    "id": "3001503294"
                                                }
                                            ],
                                            "serial": "1234AA456",
                                            "cui": "8000000000",
                                            "titlu": "Lista Mesaje disponibile din ultimele 1 zile"
                                        }
                                    },
                                    "cif este non numeric": {
                                        "description": "cif non-numeric",
                                        "value": {
                                            "eroare": "CIF introdus= aaa nu este un numar",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "numar de zile este non numeric": {
                                        "description": "numar de zile non-numeric",
                                        "value": {
                                            "eroare": "Numarul de zile introdus= aaa nu este un numar intreg",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "numar de zile incorect": {
                                        "description": "parametrul zile nu este intre 1 si 60",
                                        "value": {
                                            "eroare": "Numarul de zile trebuie sa fie intre 1 si 60",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "parametrul filtru invalid": {
                                        "description": "parametrul filtru este completat dar este invalid",
                                        "value": {
                                            "eroare": "Valorile acceptate pentru parametrul filtru sunt E, T, P sau R",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "nu aveti drept pentru acest cif": {
                                        "description": "cif fara drept",
                                        "value": {
                                            "eroare": "Nu aveti drept in SPV pentru CIF=8000000000",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "lipsa drepturi SPV": {
                                        "description": "nu aveti drepturi in SPV pentru nici un cif",
                                        "value": {
                                            "eroare": "Nu exista niciun CIF pentru care sa aveti drept in SPV",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "nu exista mesaje": {
                                        "description": "nu exista mesaje in intervalul de zile mentionat",
                                        "value": {
                                            "eroare": "Nu exista mesaje in ultimele 15 zile",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "limita mesaje in pagina atinsa": {
                                        "description": "a fost atinsa limita de mesaje in pagina",
                                        "value": {
                                            "eroare": "Lista de mesaje este mai mare decat numarul de 500 elemente permise in pagina. Folositi endpoint-ul cu paginatie.",
                                            "titlu": "Lista Mesaje"
                                        }
                                    },
                                    "limita apeluri zilnice atinsa": {
                                        "description": "a fost atinsa limita de apeluri zilnice",
                                        "value": {
                                            "eroare": "S-au facut deja 1000 interogari de lista mesaje de catre utilizator in cursul zilei",
                                            "titlu": "Lista Mesaje"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/descarcare": {
            "get": {
                "tags": [
                    "eFactura Download"
                ],
                "operationId": "getDescarcare",
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "description": "Specifica indexul de descarcare al facturii",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": 1
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Solicitare incorecta",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "$ref": "#/components/schemas/GeneralErrorMessage"
                                },
                                "examples": {
                                    "nu ati completat parametrul standard": {
                                        "summary": "lipsa parametru standard",
                                        "description": "nu ati completat parametrul standard",
                                        "value": {
                                            "timestamp": "05-08-2021 12:04:01",
                                            "status": 400,
                                            "error": "Bad Request",
                                            "message": "Parametrul id este obligatoriu"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "Operatie realizata cu succes",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "string"
                                },
                                "examples": {
                                    "factura a fost descarcata cu succes": {
                                        "summary": "descarcare cu succes",
                                        "description": "factura a fost descarcata cu succes",
                                        "value": "fisier cu extensia zip. ex: 123.zip"
                                    },
                                    "id-ul furnizat nu este valid": {
                                        "summary": "id invalid",
                                        "description": "id-ul furnizat nu este valid",
                                        "value": {
                                            "eroare": "Id descarcare introdus= 123a nu este un numar intreg",
                                            "titlu": "Descarcare mesaj"
                                        }
                                    },
                                    "a fost atinsa limita de apeluri zilnice": {
                                        "summary": "limita apeluri zilnice atinsa",
                                        "description": "a fost atinsa limita de apeluri zilnice",
                                        "value": "{\"eroare\":\"S-au facut deja 10 descarcari de mesaj in cursul zilei\",\"titlu\":\"Descarcare mesaj\"}"
                                    },
                                    "nu aveti dreptul sa descarcati factura cu id-ul mentionat in request": {
                                        "summary": "certificat fara drepturi",
                                        "description": "nu aveti dreptul sa descarcati factura cu id-ul mentionat in request",
                                        "value": {
                                            "eroare": "Nu aveti dreptul sa descarcati acesta factura",
                                            "titlu": "Descarcare mesaj"
                                        }
                                    },
                                    "nu exista nici o factura pentru id-ul solicitat": {
                                        "summary": "id fara factura",
                                        "description": "nu exista nici o factura pentru id-ul solicitat",
                                        "value": {
                                            "eroare": "Pentru id=21 nu exista inregistrata nici o factura",
                                            "titlu": "Descarcare mesaj"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "GeneralErrorMessage": {
                "type": "object",
                "properties": {
                    "timestamp": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "status": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "error": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    },
                    "eroare": {
                        "type": "string"
                    },
                    "titlu": {
                        "type": "string"
                    }
                }
            },
            "EfacturaJsonErrorMessage": {
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string"
                    }
                }
            },
            "EfacturaResponseHeader": {
                "required": [
                    "stare",
                    "trace_id"
                ],
                "type": "object",
                "properties": {
                    "stare": {
                        "type": "string"
                    },
                    "Messages": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/EfacturaJsonErrorMessage"
                        }
                    },
                    "trace_id": {
                        "type": "string"
                    }
                }
            },
            "EfacturaXmlErrorMessage": {
                "type": "object",
                "properties": {
                    "errorMessage": {
                        "type": "string",
                        "xml": {
                            "attribute": true
                        }
                    }
                }
            },
            "EfacturaXmlHeader": {
                "type": "object",
                "properties": {
                    "errors": {
                        "type": "array",
                        "xml": {
                            "name": "Errors"
                        },
                        "items": {
                            "$ref": "#/components/schemas/EfacturaXmlErrorMessage"
                        }
                    },
                    "stare": {
                        "type": "string",
                        "xml": {
                            "attribute": true
                        }
                    },
                    "idDescarcare": {
                        "type": "string",
                        "xml": {
                            "name": "id_descarcare",
                            "attribute": true
                        }
                    },
                    "dateResponse": {
                        "type": "string",
                        "xml": {
                            "attribute": true
                        }
                    },
                    "executionStatus": {
                        "type": "integer",
                        "format": "int32",
                        "xml": {
                            "name": "ExecutionStatus",
                            "attribute": true
                        }
                    },
                    "indexIncarcare": {
                        "type": "integer",
                        "format": "int64",
                        "xml": {
                            "name": "index_incarcare",
                            "attribute": true
                        }
                    }
                },
                "xml": {
                    "name": "header"
                }
            },
            "EfacturaDetailedMessage": {
                "type": "object",
                "properties": {
                    "data_creare": {
                        "type": "string"
                    },
                    "cif": {
                        "type": "string"
                    },
                    "id_solicitare": {
                        "type": "string"
                    },
                    "detalii": {
                        "type": "string"
                    },
                    "tip": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                }
            }
        }
    }
}